### ISSUE TITLE
bigram is not reproducible

### ISSUE THREAD

**Issue by czchen** [libzhuyin/libzhuyin#7] opened 2015-02-26 12:13 UTC
Currently Debian is working on [reproducible builds](https://wiki.debian.org/ReproducibleBuilds), but the bigram.db in libzhuyin is not [reproducible](https://reproducible.debian.net/rb-pkg/libzhuyin.html). Is it possible to modify so that libzhuyin can be reproducible?

**Comment by epico** [comment] 2015-02-27 02:54
I think libzhuyin may not use not reproducible code, but I might be wrong.
I suspect it is caused by Berkeley DB, is other Berkeley DB data reproducible?

**Comment by epico** [comment] 2017-09-14 02:59
This project has been merged into libpinyin and ibus-libzhuyin.
Please try libpinyin and ibus-libzhuyin instead, thanks!

**Closed by epico** 2017-09-14 02:59 UTC
